export const users = [
  {
    id: 1,
    name: 'Константин',
    password: '12345',
    email: 'konstantin@gmail.com',
    about: "Немного о себе, я админ.",
    role: 'admin',
  },
  {
    id: 2,
    name: 'Иван',
    password: '12345',
    email: 'ivan@gmail.com',
    about: "Немного о себе, я Иван - менеджер.",
    role: 'user',
  },
  {
    id: 3,
    name: 'Валентина',
    password: '12345',
    email: 'valentina@gmail.com',
    about: "Немного о себе, я Валентина - глав.бух.",
    role: 'user',
  },
  {
    id: 4,
    name: 'Максим',
    password: '12345',
    email: 'maxs@gmail.com',
    about: "Немного о себе, я Максим - охранник.",
    role: 'user',
  },
  {
    id: 5,
    name: 'Ольга',
    password: '12345',
    email: 'olga@gmail.com',
    about: "Немного о себе, я Ольга - секретарь.",
    role: 'user',
  },
]